Repository arthurghz/Intelig-ncia_Artificial_Godot, pull requests merged in 2020-05, with the labels that each got.

#32 Threads funcionando como deveriam
  Scripts/Grid.gd
  Scripts/Tilemap.gd
Labels: bug

#34 Arrumando funcionalidade do AStar com hamburguers aleatorios
  Scripts/Tilemap.gd
Labels: bug

#39 Arrumado AStar quando jogo reiniciado e principio da IA implementada
  Assets/img/IA.png
  Scenes/Coin.tscn
  Scenes/IA.tscn
  Scripts/Coin.gd
  Scripts/Grid.gd
  Scripts/IA.gd
  Scripts/Tilemap.gd
Labels: bug, enhancement

#44 Task 19 criar tie breaker
  Scenes/Grid.tscn
  Scenes/Player.tscn
  Scripts/Grid.gd
  Scripts/Tilemap.gd
Labels: bug, enhancement

#45 IA funcionando, comentarios no codigo e pequenos ajustes
  Scenes/End.tscn
  Scenes/Grid.tscn
  Scenes/Player.tscn
  Scenes/menu.tscn
  Scenes/png.tscn
  Scripts/Coin.gd
  Scripts/End.gd
  Scripts/Grid.gd
  Scripts/IA.gd
  Scripts/Iniciar.gd
  Scripts/Jogador.gd
  Scripts/Sair.gd
  Scripts/Tilemap.gd
Labels: enhancement
